title: Huang Meiyu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>
  Discover the story behind data,<br>
  One dataset at a time.<br>
  I am driven to discover stories behind data to create insighful decisions. 
  </p>
  <a href="https://github.com/waterpetals/waterpetals.github.io">MY PROJECTS PORTFOLIO</a>
  <br>
  <a href="https://github.com/waterpetals/waterpetals.github.io/aboutme">ABOUT ME</a>
  <br><br>
  <a href="https://www.linkedin.com/in/huang-m-a0741416a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
